name: Trigger auto deployment for azure-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/azure-container-AutoDeployTrigger-0096c81e-1044-43d3-ab83-f55d28f81b20.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURECONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURECONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURECONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.AZURECONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZURECONTAINER_REGISTRY_PASSWORD }}
          containerAppName: azure-container
          resourceGroup: jim-llmops
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


